# Generated by Django 4.2.23 on 2025-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("event", "Event"),
                    ("social_media", "Social Media"),
                    ("other", "Other"),
                    ("webinar", "Webinar"),
                    ("referral", "Referral"),
                    ("advertisement", "Advertisement"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
