# Generated by Django 6.0.3 on 2026-03-06 18:00

import django.db.models.deletion
import horilla.registry.limiters
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_automations', '0003_alter_automationcondition_created_at_and_more'),
        ('horilla_core', '0011_alter_activetab_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horillaautomation',
            name='model',
            field=models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('automation_models'), on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Module'),
        ),
    ]
