# Generated by Django 4.2.23 on 2025-11-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorillaAboutSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "About System",
                "permissions": (
                    ("can_view_horilla_about_system", "Can View About System"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
