# Generated by Django 6.0 on 2026-02-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0008_alter_horillaattachment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='date_time_format',
            field=models.CharField(choices=[('%Y-%m-%d %H:%M:%S', 'YYYY-MM-DD HH:MM:SS (2006-10-25 13:45:00)'), ('%Y-%m-%d %I:%M:%S %p', 'YYYY-MM-DD HH:MM:SS AM/PM (2006-10-25 01:45:00 PM)'), ('%m/%d/%Y %H:%M', 'MM/DD/YYYY HH:MM (10/25/2006 13:45)'), ('%d %b %Y %H:%M:%S', 'DD Mon YYYY HH:MM:SS (25 Oct 2006 13:45:00)'), ('%d %B %Y %I:%M %p', 'DD Full Month YYYY HH:MM AM/PM (25 October 2006 01:45 PM)'), ('%b %d, %Y %I:%M:%S %p', 'Mon DD, YYYY HH:MM:SS AM/PM (Oct 25, 2006 01:45:00 PM)'), ('%d-%m-%Y %H:%M:%S', 'DD-MM-YYYY HH:MM:SS (25-10-2006 13:45:00)'), ('%Y/%m/%d %H:%M:%S', 'YYYY/MM/DD HH:MM:SS (2006/10/25 13:45:00)'), ('%Y-%m-%dT%H:%M:%S', 'ISO 8601 (2006-10-25T13:45:00)'), ('%Y-%m-%d %H:%M:%S.%f', 'YYYY-MM-DD HH:MM:SS.mmmmmm (2006-10-25 13:45:00.123456)'), ('%A, %d %B %Y %I:%M %p', 'Full Weekday, DD Full Month YYYY HH:MM AM/PM (Wednesday, 25 October 2006 01:45 PM)')], default='%Y-%m-%d %H:%M:%S', help_text='Select your preferred date time format.', max_length=100, verbose_name='Date Time Format'),
        ),
        migrations.AddField(
            model_name='savedfilterlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When set, this filter is available to all users in this list/position.'),
        ),
        migrations.AddIndex(
            model_name='savedfilterlist',
            index=models.Index(fields=['model_name', 'is_public'], name='horilla_cor_model_n_81759f_idx'),
        ),
        migrations.AddField(
            model_name='quickfilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quickfilter',
            unique_together={('user', 'app_label', 'model_name', 'field_name')},
        ),
    ]
