# Generated by Django 6.0 on 2026-02-20 17:02

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0009_quickfilter_company_date_time_format_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kanbangroupby',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kanbangroupby',
            name='view_type',
            field=models.CharField(choices=[('kanban', 'Kanban'), ('group_by', 'Group By')], default='kanban', help_text='Whether this setting is for Kanban view or Group By view.', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subroles', to='horilla_core.role', verbose_name='Parent Role'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbangroupby',
            unique_together={('model_name', 'app_label', 'user', 'view_type')},
        ),
        migrations.CreateModel(
            name='DetailFieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('url_name', models.CharField(default='', max_length=100)),
                ('header_fields', models.JSONField(default=list)),
                ('details_fields', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_field_visibility', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'app_label', 'model_name', 'url_name')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
