# Generated by Django 6.0 on 2026-02-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_dashboard', '0002_alter_componentcriteria_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultHomeLayoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(blank=True, default=dict, help_text='For default home: {"kpi": ["default-kpi-0", ...], "chartsAndTables": [...]}. For dashboard: {"kpi": [id, ...], "components": [id, ...]}.')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_layout_orders', to='horilla_dashboard.dashboard', verbose_name='Dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Default Home Layout Order',
                'verbose_name_plural': 'Default Home Layout Orders',
                'constraints': [models.UniqueConstraint(fields=('user', 'dashboard'), name='unique_user_dashboard_layout_order'), models.UniqueConstraint(condition=models.Q(('dashboard__isnull', True)), fields=('user',), name='unique_user_default_home_layout_order')],
                'unique_together': {('user', 'dashboard')},
            },
        ),
    ]
