# Generated by Django 6.0 on 2026-02-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='source',
        ),
    ]
