# Generated by Django 4.2.23 on 2025-12-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="opportunities.opportunitystage",
                verbose_name="Stage",
            ),
        ),
    ]
