# Generated by Django 4.2.23 on 2025-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_scoringrule_scoringcriterion_scoringcondition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("event", "Event"),
                    ("campaign", "Campaign"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("social_media", "Social Media"),
                    ("partner", "Partner"),
                    ("other", "Other"),
                ],
                max_length=100,
                verbose_name="Lead Source",
            ),
        ),
    ]
